name: Reusable Workflow 1

on:
  workflow_call:
    inputs:
      example_input:
        description: 'An example input for the reusable workflow'
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "This is an example input: ${{ inputs.example_input }}"